### PR TITLE
Enable Pest expectations in route testing

### PR DESCRIPTION
**Pull request by ngmy**
I think it would be useful if this plugin could be used in combination with Pest's snapshot testing (`toMatchSnapshot()`).

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Nice! Could you also add a test for this?

**Comment by ngmy** [comment]
I added a test. How does it look?

I got the following error when I did `new RouteTestingTestCall(test('description'));` or `routeTesting('description');`  in the test, so I created a dummy `RouteTestingTestCall` instance:

```
  Undefined array key "file"

  at vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:256
    252▕      */
    253▕     protected function forwardsTo($method)
    254▕     {
    255▕         return fn (...$arguments) => static::$app
  ➜ 256▕             ? $this->{$method}(...$arguments)
    257▕             : false;
    258▕     }
    259▕
    260▕     /**
```

**Comment by ngmy** [comment]
Please wait.

**Comment by ngmy** [comment]
Sorry, I'll redo with #17.

**Pull request closed without merging**
